# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1533709834);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1533709954);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1533716206);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1533709714);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1533709594);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1533710074);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 1);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1533709447);
user_pref("browser.laterrun.bookkeeping.sessionCount", 3);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 42);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 8);
user_pref("browser.reader.detectedFirstArticle", true);
user_pref("browser.safebrowsing.provider.google.lastupdatetime", "1533709536578");
user_pref("browser.safebrowsing.provider.google.nextupdatetime", "1533711234578");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1533709506490");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1533713106490");
user_pref("browser.search.countryCode", "IN");
user_pref("browser.search.region", "IN");
user_pref("browser.slowStartup.averageTime", 51864);
user_pref("browser.slowStartup.samples", 3);
user_pref("browser.startup.homepage_override.buildID", "20180319174659");
user_pref("browser.startup.homepage_override.mstone", "52.7.2");
user_pref("browser.tabs.remote.autostart.2", true);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"PanelUI-contents\":[\"edit-controls\",\"zoom-controls\",\"new-window-button\",\"privatebrowsing-button\",\"save-page-button\",\"print-button\",\"history-panelmenu\",\"fullscreen-button\",\"find-button\",\"preferences-button\",\"add-ons-button\",\"developer-button\",\"sync-button\"],\"addon-bar\":[\"addonbar-closebutton\",\"status-bar\"],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"urlbar-container\",\"search-container\",\"bookmarks-menu-button\",\"downloads-button\",\"home-button\",\"pocket-button\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"toolbar-menubar\":[\"menubar-items\"]},\"seen\":[\"pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\",\"PanelUI-contents\",\"addon-bar\"],\"currentVersion\":6,\"newElementCount\":0}");
user_pref("browser.urlbar.daysBeforeHidingSuggestionsPrompt", 3);
user_pref("browser.urlbar.lastSuggestionsPromptDate", 20180808);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1533709564828");
user_pref("datareporting.sessions.current.activeTicks", 0);
user_pref("datareporting.sessions.current.firstPaint", 25259);
user_pref("datareporting.sessions.current.main", 3316);
user_pref("datareporting.sessions.current.startTime", "1533716690700");
user_pref("datareporting.sessions.current.totalTime", 25);
user_pref("datareporting.sessions.currentIndex", 2);
user_pref("datareporting.sessions.previous.0", "{\"s\":1533709376590,\"a\":109,\"t\":1240,\"c\":false,\"m\":12197,\"fp\":96515,\"sr\":127010}");
user_pref("datareporting.sessions.previous.1", "{\"s\":1533716168630,\"a\":4,\"t\":43,\"c\":false,\"m\":2801,\"fp\":19180,\"sr\":18119}");
user_pref("e10s.rollout.cohort", "test");
user_pref("e10s.rollout.cohortSample", "0.888369");
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{\"webcompat@mozilla.org\":{\"version\":\"1.0\",\"type\":\"extension\",\"descriptor\":\"/usr/lib64/firefox/browser/features/webcompat@mozilla.org.xpi\",\"multiprocessCompatible\":true,\"runInSafeMode\":true,\"dependencies\":[],\"hasEmbeddedWebExtension\":false},\"e10srollout@mozilla.org\":{\"version\":\"1.10\",\"type\":\"extension\",\"descriptor\":\"/usr/lib64/firefox/browser/features/e10srollout@mozilla.org.xpi\",\"multiprocessCompatible\":true,\"runInSafeMode\":true,\"dependencies\":[],\"hasEmbeddedWebExtension\":false},\"firefox@getpocket.com\":{\"version\":\"1.0.5\",\"type\":\"extension\",\"descriptor\":\"/usr/lib64/firefox/browser/features/firefox@getpocket.com.xpi\",\"multiprocessCompatible\":true,\"runInSafeMode\":true,\"dependencies\":[],\"hasEmbeddedWebExtension\":false},\"aushelper@mozilla.org\":{\"version\":\"2.0\",\"type\":\"extension\",\"descriptor\":\"/usr/lib64/firefox/browser/features/aushelper@mozilla.org.xpi\",\"multiprocessCompatible\":true,\"runInSafeMode\":true,\"dependencies\":[],\"hasEmbeddedWebExtension\":false}}");
user_pref("extensions.databaseSchema", 19);
user_pref("extensions.e10s.rollout.blocklist", "{dc572301-7619-498c-a57d-39143191b318};support@lastpass.com;");
user_pref("extensions.e10s.rollout.hasAddon", false);
user_pref("extensions.e10s.rollout.policy", "51set1");
user_pref("extensions.e10sBlockedByAddons", false);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:52.7.2");
user_pref("extensions.getAddons.cache.lastUpdate", 1533709839);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "52.7.2");
user_pref("extensions.lastPlatformVersion", "52.7.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.xpiState", "{\"app-system-defaults\":{\"webcompat@mozilla.org\":{\"d\":\"/usr/lib64/firefox/browser/features/webcompat@mozilla.org.xpi\",\"e\":true,\"v\":\"1.0\",\"st\":1521482389000},\"e10srollout@mozilla.org\":{\"d\":\"/usr/lib64/firefox/browser/features/e10srollout@mozilla.org.xpi\",\"e\":true,\"v\":\"1.10\",\"st\":1521482389000},\"firefox@getpocket.com\":{\"d\":\"/usr/lib64/firefox/browser/features/firefox@getpocket.com.xpi\",\"e\":true,\"v\":\"1.0.5\",\"st\":1521482389000},\"aushelper@mozilla.org\":{\"d\":\"/usr/lib64/firefox/browser/features/aushelper@mozilla.org.xpi\",\"e\":true,\"v\":\"2.0\",\"st\":1521482389000}},\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib64/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi\",\"e\":true,\"v\":\"52.7.2\",\"st\":1521482389000}}}");
user_pref("idle.lastDailyNotification", 1533710792);
user_pref("media.gmp-manager.buildID", "20180319174659");
user_pref("media.gmp-manager.lastCheck", 1533709545);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 122334);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("services.blocklist.addons.checked", 1533584503);
user_pref("services.blocklist.clock_skew_seconds", 125452);
user_pref("services.blocklist.gfx.checked", 1533584503);
user_pref("services.blocklist.last_etag", "\"1533550294490\"");
user_pref("services.blocklist.last_update_seconds", 1533584503);
user_pref("services.blocklist.onecrl.checked", 1533584503);
user_pref("services.blocklist.plugins.checked", 1533584503);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("toolkit.startup.last_success", 1533716694);
user_pref("toolkit.telemetry.cachedClientID", "a044cd84-ebaa-4a01-afc9-8c1321bcdbd2");
user_pref("toolkit.telemetry.previousBuildID", "20180319174659");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
